name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - tensorflow-cpu=2.13.0
  - keras=2.13.1
  - chardet=5.0.0
  - requests=2.28.2
  - charset-normalizer=3.2.0
  - flask=3.0.2
  - gunicorn=20.1.0
  - pip
  - nomkl
  - conda-forge::conda
